[mysql]
host="127.0.0.1"
port=3306
database="stocks_dashboard"
user="root"
password="SetRootPasswordHere"


[mysql1]
host="172-31-24-163"
port=3306
database="stocks_dashboard"
user="root"
password="SetRootPasswordHere"


[mysql2]
host="localhost"
port=3306
database="stocks dashboard"
user="root"
password=""


[mysql3]
host="localhost"
port=3306
database="mutual_fund_dashboard"
user="root"
password=""


[mysql_aws_rds]
host="db-temp-stocks-dashboard-2.cujacys8oys0.us-west-2.rds.amazonaws.com"
port=3306
database="stocks_dashboard_temp"
user="root"
password="SetRootPasswordHere"



[admin_ch]
admin_ch="chetan"


[db_table]
master_table = "master_sheet_table"
filter_table = "master_filter"
query_table = "query_storage"
user_table = "user_login"
news_table="news"
sentiment_table="sentiment_analysis"
mf_sheet_table="mf_sheet_table"
mf_filter_table="mf_filter_table"
mf_rolling_return_table="mf_rr_sheet_table"
portfolio_table = ""
